import { createElement } from '@lwc/engine-dom';
import DemoDashboard from 'c/demoDashboard';

// Stub child component used inside demoDashboard to avoid module-not-found during tests
if (!customElements.get('c-projects')) {
    customElements.define('c-projects', class extends HTMLElement {
        connectedCallback() {
            this.attachShadow({ mode: 'open' });
        }
    });
}

describe('c-demo-dashboard', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-demo-dashboard', {
            is: DemoDashboard
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});